---
name: "Make Nightly AppImage Release"
description: "Releases artifacts under the tag nightly"

inputs:
  github_token:
    description: 'We need GITHUB_TOKEN to be able to delete the previous nightly release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Read version and get date
      shell: sh
      run: |
        if [ ! -f ./appinfo ]; then
          >&2 echo "ERROR: No ./appinfo file found!"
          exit 1
        fi
        APPNAME=$(awk -F'=' '/X-AppImage-Name/{print $2; exit}' ./appinfo)
        VERSION=$(awk -F'=' '/X-AppImage-Version/{print $2; exit}' ./appinfo)
        if [ -z "$APPNAME" ]; then
          >&2 echo "ERROR: ./appinfo is missing X-AppImage-Name"
          exit 1
        elif [ -z "$VERSION" ]; then
          >&2 echo "ERROR: ./appinfo is missing X-AppImage-Version"
          exit 1
        fi
        echo "APPNAME=$APPNAME" >> "${GITHUB_ENV}"
        echo "VERSION=$VERSION" >> "${GITHUB_ENV}"
        echo "DATE=$(date +'%Y-%m-%d_%s')" >> "${GITHUB_ENV}"

    - name: Delete previous nightly release
      shell: sh
      continue-on-error: true
      run: gh release delete "nightly" --repo "${GITHUB_REPOSITORY}" --cleanup-tag -y && sleep 5
      env:
        GH_TOKEN: "${{ inputs.github_token }}"

    - name: Release Artifacts
      uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
      with:
        name: "Nightly Build (${{ env.DATE }})"
        tag_name: "nightly"
        prerelease: true
        draft: false
        generate_release_notes: false
        make_latest: false
        files: |
          *.AppImage*
